This tutorial is about tuning hyperparameters inside the jupyter notebook:

Reviewed by: Zhi Zhang

Objectives:
<ul>
<li>Get familiar with some common libraries for Data Analysis in Python such as Pandas.</li>
<li>Get familiar with AWS SageMaker to train Machine Learning models using the cloud</li>
<li>Get familiar with Jupyter Notebooks</li>
</ul>

# Install libraries

In [21]:
# Install SageMaker via jupyter notebook
!pip install sagemaker
# Install pandas and numpy jupyter notebook
!pip install pandas
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sagemaker in /home/liudayubob/.local/lib/python3.10/site-packages (2.232.2)
Requirement already satisfied: cloudpickle==2.2.1 in /home/liudayubob/.local/lib/python3.10/site-packages (from sagemaker) (2.2.1)
Requirement already satisfied: sagemaker-mlflow in /home/liudayubob/.local/lib/python3.10/site-packages (from sagemaker) (0.1.0)
Requirement already satisfied: packaging>=20.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from sagemaker) (24.1)
Requirement already satisfied: docker in /home/liudayubob/.local/lib/python3.10/site-packages (from sagemaker) (7.1.0)
Requirement already satisfied: tqdm in /home/liudayubob/.local/lib/python3.10/site-packages (from sagemaker) (4.66.5)
Requirement already satisfied: boto3<2.0,>=1.34.142 in /home/liudayubob/.local/lib/python3.10/site-packages (from sagemaker) (1.34.162)
Requirement already satisfied: google-pasta in /home/liudayubob/.local/lib/python3.10/site-packages (from sagemaker) (0.2.0)
Requirement already satisfied: numpy<2.0,>=1.9.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from sagemaker) (1.26.4)
Requirement already satisfied: importlib-metadata<7.0,>=1.4.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from sagemaker) (6.11.0)
Requirement already satisfied: pathos in /home/liudayubob/.local/lib/python3.10/site-packages (from sagemaker) (0.3.3)
Requirement already satisfied: urllib3<3.0.0,>=1.26.8 in /home/liudayubob/.local/lib/python3.10/site-packages (from sagemaker) (2.2.2)
Requirement already satisfied: attrs<24,>=23.1.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from sagemaker) (23.2.0)
Requirement already satisfied: protobuf<5.0,>=3.12 in /home/liudayubob/.local/lib/python3.10/site-packages (from sagemaker) (4.25.5)
Requirement already satisfied: pandas in /home/liudayubob/.local/lib/python3.10/site-packages (from sagemaker) (2.2.3)
Requirement already satisfied: pyyaml~=6.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from sagemaker) (6.0.2)
Requirement already satisfied: tblib<4,>=1.7.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from sagemaker) (3.0.0)
Requirement already satisfied: sagemaker-core<2.0.0,>=1.0.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from sagemaker) (1.0.10)
Requirement already satisfied: requests in /home/liudayubob/.local/lib/python3.10/site-packages (from sagemaker) (2.32.3)
Requirement already satisfied: platformdirs in /home/liudayubob/.local/lib/python3.10/site-packages (from sagemaker) (4.3.6)
Requirement already satisfied: psutil in /home/liudayubob/.local/lib/python3.10/site-packages (from sagemaker) (6.0.0)
Requirement already satisfied: smdebug-rulesconfig==1.0.1 in /home/liudayubob/.local/lib/python3.10/site-packages (from sagemaker) (1.0.1)
Requirement already satisfied: schema in /home/liudayubob/.local/lib/python3.10/site-packages (from sagemaker) (0.7.7)
Requirement already satisfied: jsonschema in /home/liudayubob/.local/lib/python3.10/site-packages (from sagemaker) (4.23.0)
Requirement already satisfied: botocore<1.35.0,>=1.34.162 in /home/liudayubob/.local/lib/python3.10/site-packages (from boto3<2.0,>=1.34.142->sagemaker) (1.34.162)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/liudayubob/.local/lib/python3.10/site-packages (from boto3<2.0,>=1.34.142->sagemaker) (1.0.1)
Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from boto3<2.0,>=1.34.142->sagemaker) (0.10.2)
Requirement already satisfied: zipp>=0.5 in /usr/lib/python3/dist-packages (from importlib-metadata<7.0,>=1.4.0->sagemaker) (1.0.0)
Requirement already satisfied: mock<5.0,>4.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from sagemaker-core<2.0.0,>=1.0.0->sagemaker) (4.0.3)
Requirement already satisfied: pydantic<3.0.0,>=1.7.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from sagemaker-core<2.0.0,>=1.0.0->sagemaker) (2.9.2)
Requirement already satisfied: rich<14.0.0,>=13.0.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from sagemaker-core<2.0.0,>=1.0.0->sagemaker) (13.9.2)
Requirement already satisfied: referencing>=0.28.4 in /home/liudayubob/.local/lib/python3.10/site-packages (from jsonschema->sagemaker) (0.35.1)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/liudayubob/.local/lib/python3.10/site-packages (from jsonschema->sagemaker) (2024.10.1)
Requirement already satisfied: rpds-py>=0.7.1 in /home/liudayubob/.local/lib/python3.10/site-packages (from jsonschema->sagemaker) (0.20.0)
Requirement already satisfied: idna<4,>=2.5 in /home/liudayubob/.local/lib/python3.10/site-packages (from requests->sagemaker) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /home/liudayubob/.local/lib/python3.10/site-packages (from requests->sagemaker) (2024.8.30)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/liudayubob/.local/lib/python3.10/site-packages (from requests->sagemaker) (3.4.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from google-pasta->sagemaker) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/liudayubob/.local/lib/python3.10/site-packages (from pandas->sagemaker) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /home/liudayubob/.local/lib/python3.10/site-packages (from pandas->sagemaker) (2024.2)
Requirement already satisfied: pytz>=2020.1 in /home/liudayubob/.local/lib/python3.10/site-packages (from pandas->sagemaker) (2024.2)
Requirement already satisfied: multiprocess>=0.70.17 in /home/liudayubob/.local/lib/python3.10/site-packages (from pathos->sagemaker) (0.70.17)
Requirement already satisfied: dill>=0.3.9 in /home/liudayubob/.local/lib/python3.10/site-packages (from pathos->sagemaker) (0.3.9)
Requirement already satisfied: pox>=0.3.5 in /home/liudayubob/.local/lib/python3.10/site-packages (from pathos->sagemaker) (0.3.5)
Requirement already satisfied: ppft>=1.7.6.9 in /home/liudayubob/.local/lib/python3.10/site-packages (from pathos->sagemaker) (1.7.6.9)
Requirement already satisfied: mlflow>=2.8 in /home/liudayubob/.local/lib/python3.10/site-packages (from sagemaker-mlflow->sagemaker) (2.17.0)
Requirement already satisfied: mlflow-skinny==2.17.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from mlflow>=2.8->sagemaker-mlflow->sagemaker) (2.17.0)
Requirement already satisfied: markdown<4,>=3.3 in /home/liudayubob/.local/lib/python3.10/site-packages (from mlflow>=2.8->sagemaker-mlflow->sagemaker) (3.7)
Requirement already satisfied: pyarrow<18,>=4.0.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from mlflow>=2.8->sagemaker-mlflow->sagemaker) (17.0.0)
Requirement already satisfied: graphene<4 in /home/liudayubob/.local/lib/python3.10/site-packages (from mlflow>=2.8->sagemaker-mlflow->sagemaker) (3.3)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from mlflow>=2.8->sagemaker-mlflow->sagemaker) (2.0.35)
Requirement already satisfied: matplotlib<4 in /home/liudayubob/.local/lib/python3.10/site-packages (from mlflow>=2.8->sagemaker-mlflow->sagemaker) (3.9.2)
Requirement already satisfied: gunicorn<24 in /home/liudayubob/.local/lib/python3.10/site-packages (from mlflow>=2.8->sagemaker-mlflow->sagemaker) (23.0.0)
Requirement already satisfied: Flask<4 in /home/liudayubob/.local/lib/python3.10/site-packages (from mlflow>=2.8->sagemaker-mlflow->sagemaker) (3.0.3)
Requirement already satisfied: scipy<2 in /home/liudayubob/.local/lib/python3.10/site-packages (from mlflow>=2.8->sagemaker-mlflow->sagemaker) (1.14.1)
Requirement already satisfied: scikit-learn<2 in /home/liudayubob/.local/lib/python3.10/site-packages (from mlflow>=2.8->sagemaker-mlflow->sagemaker) (1.5.2)
Requirement already satisfied: Jinja2<4,>=2.11 in /home/liudayubob/.local/lib/python3.10/site-packages (from mlflow>=2.8->sagemaker-mlflow->sagemaker) (3.1.4)
Requirement already satisfied: alembic!=1.10.0,<2 in /home/liudayubob/.local/lib/python3.10/site-packages (from mlflow>=2.8->sagemaker-mlflow->sagemaker) (1.13.3)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from mlflow-skinny==2.17.0->mlflow>=2.8->sagemaker-mlflow->sagemaker) (1.27.0)
Requirement already satisfied: click<9,>=7.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from mlflow-skinny==2.17.0->mlflow>=2.8->sagemaker-mlflow->sagemaker) (8.1.7)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from mlflow-skinny==2.17.0->mlflow>=2.8->sagemaker-mlflow->sagemaker) (0.34.0)
Requirement already satisfied: cachetools<6,>=5.0.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from mlflow-skinny==2.17.0->mlflow>=2.8->sagemaker-mlflow->sagemaker) (5.5.0)
Requirement already satisfied: gitpython<4,>=3.1.9 in /home/liudayubob/.local/lib/python3.10/site-packages (from mlflow-skinny==2.17.0->mlflow>=2.8->sagemaker-mlflow->sagemaker) (3.1.43)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from mlflow-skinny==2.17.0->mlflow>=2.8->sagemaker-mlflow->sagemaker) (0.5.1)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from mlflow-skinny==2.17.0->mlflow>=2.8->sagemaker-mlflow->sagemaker) (1.27.0)
Requirement already satisfied: pydantic-core==2.23.4 in /home/liudayubob/.local/lib/python3.10/site-packages (from pydantic<3.0.0,>=1.7.0->sagemaker-core<2.0.0,>=1.0.0->sagemaker) (2.23.4)
Requirement already satisfied: typing-extensions>=4.6.1 in /home/liudayubob/.local/lib/python3.10/site-packages (from pydantic<3.0.0,>=1.7.0->sagemaker-core<2.0.0,>=1.0.0->sagemaker) (4.12.2)
Requirement already satisfied: annotated-types>=0.6.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from pydantic<3.0.0,>=1.7.0->sagemaker-core<2.0.0,>=1.0.0->sagemaker) (0.7.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from rich<14.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.0->sagemaker) (2.18.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from rich<14.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.0->sagemaker) (3.0.0)
Requirement already satisfied: Mako in /home/liudayubob/.local/lib/python3.10/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8->sagemaker-mlflow->sagemaker) (1.3.5)
Requirement already satisfied: Werkzeug>=3.0.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from Flask<4->mlflow>=2.8->sagemaker-mlflow->sagemaker) (3.0.4)
Requirement already satisfied: blinker>=1.6.2 in /home/liudayubob/.local/lib/python3.10/site-packages (from Flask<4->mlflow>=2.8->sagemaker-mlflow->sagemaker) (1.8.2)
Requirement already satisfied: itsdangerous>=2.1.2 in /home/liudayubob/.local/lib/python3.10/site-packages (from Flask<4->mlflow>=2.8->sagemaker-mlflow->sagemaker) (2.2.0)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /home/liudayubob/.local/lib/python3.10/site-packages (from graphene<4->mlflow>=2.8->sagemaker-mlflow->sagemaker) (3.2.5)
Requirement already satisfied: aniso8601<10,>=8 in /home/liudayubob/.local/lib/python3.10/site-packages (from graphene<4->mlflow>=2.8->sagemaker-mlflow->sagemaker) (9.0.1)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in /home/liudayubob/.local/lib/python3.10/site-packages (from graphene<4->mlflow>=2.8->sagemaker-mlflow->sagemaker) (3.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from Jinja2<4,>=2.11->mlflow>=2.8->sagemaker-mlflow->sagemaker) (3.0.1)
Requirement already satisfied: mdurl~=0.1 in /home/liudayubob/.local/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich<14.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.0->sagemaker) (0.1.2)
Requirement already satisfied: pillow>=8 in /home/liudayubob/.local/lib/python3.10/site-packages (from matplotlib<4->mlflow>=2.8->sagemaker-mlflow->sagemaker) (10.4.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from matplotlib<4->mlflow>=2.8->sagemaker-mlflow->sagemaker) (4.54.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/liudayubob/.local/lib/python3.10/site-packages (from matplotlib<4->mlflow>=2.8->sagemaker-mlflow->sagemaker) (1.4.7)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/lib/python3/dist-packages (from matplotlib<4->mlflow>=2.8->sagemaker-mlflow->sagemaker) (2.4.7)
Requirement already satisfied: contourpy>=1.0.1 in /home/liudayubob/.local/lib/python3.10/site-packages (from matplotlib<4->mlflow>=2.8->sagemaker-mlflow->sagemaker) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /home/liudayubob/.local/lib/python3.10/site-packages (from matplotlib<4->mlflow>=2.8->sagemaker-mlflow->sagemaker) (0.12.1)
Requirement already satisfied: joblib>=1.2.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from scikit-learn<2->mlflow>=2.8->sagemaker-mlflow->sagemaker) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from scikit-learn<2->mlflow>=2.8->sagemaker-mlflow->sagemaker) (3.5.0)
Requirement already satisfied: greenlet!=0.4.17 in /home/liudayubob/.local/lib/python3.10/site-packages (from sqlalchemy<3,>=1.4.0->mlflow>=2.8->sagemaker-mlflow->sagemaker) (3.1.1)
Requirement already satisfied: google-auth~=2.0 in /home/liudayubob/.local/lib/python3.10/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.0->mlflow>=2.8->sagemaker-mlflow->sagemaker) (2.35.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /home/liudayubob/.local/lib/python3.10/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==2.17.0->mlflow>=2.8->sagemaker-mlflow->sagemaker) (4.0.11)
Requirement already satisfied: deprecated>=1.2.6 in /home/liudayubob/.local/lib/python3.10/site-packages (from opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.0->mlflow>=2.8->sagemaker-mlflow->sagemaker) (1.2.14)
Requirement already satisfied: opentelemetry-semantic-conventions==0.48b0 in /home/liudayubob/.local/lib/python3.10/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==2.17.0->mlflow>=2.8->sagemaker-mlflow->sagemaker) (0.48b0)
Requirement already satisfied: wrapt<2,>=1.10 in /home/liudayubob/.local/lib/python3.10/site-packages (from deprecated>=1.2.6->opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.0->mlflow>=2.8->sagemaker-mlflow->sagemaker) (1.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /home/liudayubob/.local/lib/python3.10/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==2.17.0->mlflow>=2.8->sagemaker-mlflow->sagemaker) (5.0.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/liudayubob/.local/lib/python3.10/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.0->mlflow>=2.8->sagemaker-mlflow->sagemaker) (0.4.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/liudayubob/.local/lib/python3.10/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.0->mlflow>=2.8->sagemaker-mlflow->sagemaker) (4.7.2)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /home/liudayubob/.local/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.0->mlflow>=2.8->sagemaker-mlflow->sagemaker) (0.6.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /home/liudayubob/.local/lib/python3.10/site-packages (2.2.3)
Requirement already satisfied: tzdata>=2022.7 in /home/liudayubob/.local/lib/python3.10/site-packages (from pandas) (2024.2)
Requirement already satisfied: numpy>=1.22.4 in /home/liudayubob/.local/lib/python3.10/site-packages (from pandas) (1.26.4)
Requirement already satisfied: pytz>=2020.1 in /home/liudayubob/.local/lib/python3.10/site-packages (from pandas) (2024.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/liudayubob/.local/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in /home/liudayubob/.local/lib/python3.10/site-packages (1.26.4)

# Prepare a SageMaker session

In [22]:
import sagemaker
import boto3

import numpy as np  # For matrix operations and numerical processing
import pandas as pd  # For munging tabular data
from time import gmtime, strftime
import os

region = 'eu-north-1' # use the region you are mapped to 
smclient = boto3.Session(region_name=region).client("sagemaker")
iam = boto3.client('iam', region_name=region)
sagemaker_role = iam.get_role(RoleName='SageMakerRole')['Role']['Arn']
student_id = "24188516" # use your student id 
bucket = '24188516-lab8' # use <studentid-lab8> as your bucket name
prefix = f"sagemaker/{student_id}-hpo-xgboost-dm" 
# Create an S3 bucket using the bucket variable above. The bucket creation is done using the region variable above.
# Create an object into the bucket. The object is a folder and its name is the prefix variable above. 
s3 = boto3.client('s3', region_name=region)
bucket_config = {'LocationConstraint': region}
s3.create_bucket(Bucket=bucket, CreateBucketConfiguration=bucket_config) # create the bucket in our region
s3.put_object(Bucket=bucket, Key=f"{prefix}/") # create a folder object with the prefix

BucketAlreadyOwnedByYou: An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it.

Update the code above as indicated by the comments:

# Download a dataset

Read and download the marketing dataset from UCI's ML Repository [here](https://archive.ics.uci.edu/ml/datasets/bank+marketing).

NOTE: You can download and unzip the dataset using the commands below.

In [23]:
!wget -N https://archive.ics.uci.edu/ml/machine-learning-databases/00222/bank-additional.zip
!unzip -o bank-additional.zip

--2024-10-14 16:10:09--  https://archive.ics.uci.edu/ml/machine-learning-databases/00222/bank-additional.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified
Saving to: ‘bank-additional.zip’

bank-additional.zip     [      <=>           ] 434.15K   408KB/s    in 1.1s

Last-modified header missing -- time-stamps turned off.
2024-10-14 16:10:13 (408 KB/s) - ‘bank-additional.zip’ saved [444572]

Archive:  bank-additional.zip
  inflating: bank-additional/.DS_Store
   creating: __MACOSX/
   creating: __MACOSX/bank-additional/
  inflating: __MACOSX/bank-additional/._.DS_Store
  inflating: bank-additional/.Rhistory
  inflating: bank-additional/bank-additional-full.csv
  inflating: bank-additional/bank-additional-names.txt
  inflating: bank-additional/bank-additional.csv
  inflating: __MACOSX/._bank-additional

Read the dataset into a Pandas data frame and answer the following two questions:

1. Which variables in the dataset are categorical? Give at least four variables.

2. Which variables in the dataset are numerical? Give at least four variables.

In [24]:
data = pd.read_csv("./bank-additional/bank-additional-full.csv", sep=";")
pd.set_option("display.max_columns", 500)  # Make sure we can see all of the columns
pd.set_option("display.max_rows", 50)  # Keep the output on one page
data

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,261,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,149,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,226,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,151,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,307,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,retired,married,professional.course,no,yes,no,cellular,nov,fri,334,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41184,46,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,383,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41185,56,retired,married,university.degree,no,yes,no,cellular,nov,fri,189,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41186,44,technician,married,professional.course,no,no,no,cellular,nov,fri,442,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41187,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,239,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

Process the data by adding two new indicator columns and then expands categorical columns into binary dummy columns for modelling purposes.

In [25]:
data["no_previous_contact"] = np.where(
    data["pdays"] == 999, 1, 0
)  # Indicator variable to capture when pdays takes a value of 999
data["not_working"] = np.where(
    np.in1d(data["job"], ["student", "retired", "unemployed"]), 1, 0
)  # Indicator for individuals not actively employed
model_data = pd.get_dummies(data)  # Convert categorical variables to sets of indicators
model_data

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,no_previous_contact,not_working,job_admin.,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,job_unemployed,job_unknown,marital_divorced,marital_married,marital_single,marital_unknown,education_basic.4y,education_basic.6y,education_basic.9y,education_high.school,education_illiterate,education_professional.course,education_university.degree,education_unknown,default_no,default_unknown,default_yes,housing_no,housing_unknown,housing_yes,loan_no,loan_unknown,loan_yes,contact_cellular,contact_telephone,month_apr,month_aug,month_dec,month_jul,month_jun,month_mar,month_may,month_nov,month_oct,month_sep,day_of_week_fri,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_failure,poutcome_nonexistent,poutcome_success,y_no,y_yes
0,56,261,1,999,0,1.1,93.994,-36.4,4.857,5191.0,1,0,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,False,True,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False,True,False
1,57,149,1,999,0,1.1,93.994,-36.4,4.857,5191.0,1,0,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,True,False,True,False,False,True,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False,True,False
2,37,226,1,999,0,1.1,93.994,-36.4,4.857,5191.0,1,0,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,True,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False,True,False
3,40,151,1,999,0,1.1,93.994,-36.4,4.857,5191.0,1,0,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,True,False,False,True,False,False,True,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False,True,False
4,56,307,1,999,0,1.1,93.994,-36.4,4.857,5191.0,1,0,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,True,False,False,False,False,True,False,True,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,334,1,999,0,-1.1,94.767,-50.8,1.028,4963.6,1,1,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,True,False,False,True,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,True,False,False,True
41184,46,383,1,999,0,-1.1,94.767,-50.8,1.028,4963.6,1,0,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,False,True,False,False,True,False,False,True,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,True,False,True,False
41185,56,189,2,999,0,-1.1,94.767,-50.8,1.028,4963.6,1,1,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,True,True,False,False,True,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,True,False,True,False
41186,44,442,1,999,0,-1.1,94.767,-50.8,1.028,4963.6,1,0,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,False,True,False,False,True,False,False,True,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,True,False,False,True
41187,74,239,3,999,1,-1.1,94.767,-50.8,1.028,4963.6,1,1,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,True,False,False,True,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,False,False,True,False

Remove the economic features and duration from our data as they would need to be forecasted with high precision to use as inputs in future predictions.

In [26]:
model_data = model_data.drop(
    ["duration", "emp.var.rate", "cons.price.idx", "cons.conf.idx", "euribor3m", "nr.employed"],
    axis=1,
)

In [27]:
model_data

,age,campaign,pdays,previous,no_previous_contact,not_working,job_admin.,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,job_unemployed,job_unknown,marital_divorced,marital_married,marital_single,marital_unknown,education_basic.4y,education_basic.6y,education_basic.9y,education_high.school,education_illiterate,education_professional.course,education_university.degree,education_unknown,default_no,default_unknown,default_yes,housing_no,housing_unknown,housing_yes,loan_no,loan_unknown,loan_yes,contact_cellular,contact_telephone,month_apr,month_aug,month_dec,month_jul,month_jun,month_mar,month_may,month_nov,month_oct,month_sep,day_of_week_fri,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_failure,poutcome_nonexistent,poutcome_success,y_no,y_yes
0,56,1,999,0,1,0,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,False,True,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False,True,False
1,57,1,999,0,1,0,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,True,False,True,False,False,True,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False,True,False
2,37,1,999,0,1,0,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,True,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False,True,False
3,40,1,999,0,1,0,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,True,False,False,True,False,False,True,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False,True,False
4,56,1,999,0,1,0,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,True,False,False,False,False,True,False,True,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,1,999,0,1,1,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,True,False,False,True,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,True,False,False,True
41184,46,1,999,0,1,0,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,False,True,False,False,True,False,False,True,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,True,False,True,False
41185,56,2,999,0,1,1,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,True,True,False,False,True,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,True,False,True,False
41186,44,1,999,0,1,0,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,False,True,False,False,True,False,False,True,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,True,False,False,True
41187,74,3,999,1,1,1,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,True,False,False,True,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,False,False,True,False

# Split the data into training, validation and test

We split the dataset into training (70%), validation (20%), and test (10%) datasets and convert the datasets to an appropriate format. We will use the training and validation datasets during training. Test dataset will be used to evaluate model performance after it is deployed to an endpoint.

Amazon SageMaker's XGBoost algorithm expects data in the libSVM or CSV data format. In this lab, we use the CSV format. Note that the first column must be the target variable and the CSV should not include headers. Also, notice that although repetitive it’s easier to do this after the train|validation|test split rather than before. This avoids any misalignment issues due to random reordering.

In [33]:
# Change True/False to 1/0
model_data = model_data.replace({True: 1, False: 0})

train_data, validation_data, test_data = np.split(
    model_data.sample(frac=1, random_state=1729),
    [int(0.7 * len(model_data)), int(0.9 * len(model_data))],
)

pd.concat([train_data["y_yes"], train_data.drop(["y_no", "y_yes"], axis=1)], axis=1).to_csv(
    "train.csv", index=False, header=False
)
pd.concat(
    [validation_data["y_yes"], validation_data.drop(["y_no", "y_yes"], axis=1)], axis=1
).to_csv("validation.csv", index=False, header=False)
pd.concat([test_data["y_yes"], test_data.drop(["y_no", "y_yes"], axis=1)], axis=1).to_csv(
    "test.csv", index=False, header=False
)

/home/liudayubob/.local/lib/python3.10/site-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

Copy the file to the S3 bucket created earlier for Amazon SageMaker training to pick up.

In [34]:
boto3.Session().resource("s3").Bucket(bucket).Object(
    os.path.join(prefix, "train/train.csv")
).upload_file("train.csv")
boto3.Session().resource("s3").Bucket(bucket).Object(
    os.path.join(prefix, "validation/validation.csv")
).upload_file("validation.csv")

# Setup hyperparameter tuning

Set up the the name and configuration for a hyperparameter tuning job.

In [35]:
from time import gmtime, strftime, sleep

# Names have to be unique. You will get an error if you reuse the same name
tuning_job_name = f"{student_id}-xgboost-tuningjob-03"

print(tuning_job_name)

tuning_job_config = {
    "ParameterRanges": {
        "CategoricalParameterRanges": [],
        "ContinuousParameterRanges": [
            {
                "MaxValue": "1",
                "MinValue": "0",
                "Name": "eta",
            },
            {
                "MaxValue": "10",
                "MinValue": "1",
                "Name": "min_child_weight",
            },
            {
                "MaxValue": "2",
                "MinValue": "0",
                "Name": "alpha",
            },
        ],
        "IntegerParameterRanges": [
            {
                "MaxValue": "10",
                "MinValue": "1",
                "Name": "max_depth",
            }
        ],
    },
    "ResourceLimits": {"MaxNumberOfTrainingJobs": 2, "MaxParallelTrainingJobs": 2},
    "Strategy": "Bayesian",
    "HyperParameterTuningJobObjective": {"MetricName": "validation:auc", "Type": "Maximize"},
}

24188516-xgboost-tuningjob-03

Specify the XGBoost algorithm for subsequent tuning.

In [36]:
from sagemaker.image_uris import retrieve
# Use XGBoost algorithm for training
training_image = retrieve(framework="xgboost", region=region, version="latest")

s3_input_train = "s3://{}/{}/train".format(bucket, prefix)
s3_input_validation = "s3://{}/{}/validation/".format(bucket, prefix)

training_job_definition = {
    "AlgorithmSpecification": {"TrainingImage": training_image, "TrainingInputMode": "File"},
    "InputDataConfig": [
        {
            "ChannelName": "train",
            "CompressionType": "None",
            "ContentType": "csv",
            "DataSource": {
                "S3DataSource": {
                    "S3DataDistributionType": "FullyReplicated",
                    "S3DataType": "S3Prefix",
                    "S3Uri": s3_input_train,
                }
            },
        },
        {
            "ChannelName": "validation",
            "CompressionType": "None",
            "ContentType": "csv",
            "DataSource": {
                "S3DataSource": {
                    "S3DataDistributionType": "FullyReplicated",
                    "S3DataType": "S3Prefix",
                    "S3Uri": s3_input_validation,
                }
            },
        },
    ],
    "OutputDataConfig": {"S3OutputPath": "s3://{}/{}/output".format(bucket, prefix)},
    "ResourceConfig": {"InstanceCount": 1, "InstanceType": "ml.m5.xlarge", "VolumeSizeInGB": 10},
    "RoleArn": sagemaker_role,
    "StaticHyperParameters": {
        "eval_metric": "auc",
        "num_round": "1",
        "objective": "binary:logistic",
        "rate_drop": "0.3",
        "tweedie_variance_power": "1.4",
    },
    "StoppingCondition": {"MaxRuntimeInSeconds": 43200},
}

Launch the tuning job.

In [37]:
#Launch Hyperparameter Tuning Job
smclient.create_hyper_parameter_tuning_job(
    HyperParameterTuningJobName=tuning_job_name,
    HyperParameterTuningJobConfig=tuning_job_config,
    TrainingJobDefinition=training_job_definition,
)

{'HyperParameterTuningJobArn': 'arn:aws:sagemaker:eu-north-1:489389878001:hyper-parameter-tuning-job/24188516-xgboost-tuningjob-03',
 'ResponseMetadata': {'RequestId': 'e596961f-13d0-434f-86d4-8670a68271d6',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amzn-requestid': 'e596961f-13d0-434f-86d4-8670a68271d6',
   'content-type': 'application/x-amz-json-1.1',
   'content-length': '131',
   'date': 'Mon, 14 Oct 2024 08:11:33 GMT'},
  'RetryAttempts': 0}}

Go to AWS console (SageMaker-> Training -> Hyperparameter tuning jobs) to monitor the progress of the hyperparameter tuning job ([How to monitor the progress of a job?](https://docs.aws.amazon.com/sagemaker/latest/dg/automatic-model-tuning-monitor.html)).

The tuning will normally take between 2-4 minutes. Make ensure that the tuning job is completed successfully from the console. Also check the job output inside the s3 object you created. Last, remove all the AWS resources you used in this lab.

NOTE: if the tuning job fails, check if you meet this error, ClientError: Non-numeric value 'F' found in the header line 'False,54,3,999,0,1,0,False,False,False,False,False...' of the file 'train.csv'. If so, you should convert the non-numeric values to numeric ones (i.e., True/False to 1/0). After that, rename your tuning job in the provided code and run it again.